In [3]:
import numpy as np


In [1]:
a = [1,2,3,4,5]
print(a)
type(a)

[1, 2, 3, 4, 5]


list

In [4]:
a2 = np.array(a)
print(a2)
type(a2)

[1 2 3 4 5]


numpy.ndarray

In [6]:
a2.shape

(5,)

In [7]:
c = np.array([[1,2,3,],[5,6,7]])

In [9]:
c.shape

(2, 3)

In [10]:
d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [12]:
d.shape

(12,)

In [14]:
d = d.reshape(3,4)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
d.shape

(3, 4)

In [20]:
d = d.reshape(3,2,2)

In [22]:
print(d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
